// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {keygen} from '../models';
import {main} from '../models';

export function GenerateKeys(arg1:string,arg2:keygen.KeyType):Promise<void>;

export function GetKeys():Promise<any>;

export function Greet(arg1:string):Promise<string>;

export function KeyListingBinding(arg1:main.KeyListing):Promise<void>;

export function KnownHostMatchBinding(arg1:main.KnownHostMatch):Promise<void>;

export function SaveHostDeclaration(arg1:string,arg2:main.HostDeclaration):Promise<void>;

export function UploadKey(arg1:string,arg2:Array<number>):Promise<void>;
